# Generated by Django 4.1.7 on 2024-03-18 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, unique=True, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی')),
                ('totall', models.PositiveSmallIntegerField(default=0, verbose_name='کل سوالات')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز')),
                ('percent', models.FloatField(max_length=5, verbose_name='درصد')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد سوالات درست')),
                ('wrong', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد سوالات غلط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
            ],
            options={
                'verbose_name': 'نتیجه',
                'verbose_name_plural': 'نتایج',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, unique=True, verbose_name='سوال')),
                ('option1', models.CharField(max_length=50, verbose_name='گزینه اول')),
                ('option2', models.CharField(max_length=50, verbose_name='گزینه دوم')),
                ('option3', models.CharField(max_length=50, verbose_name='گزینه سوم')),
                ('option4', models.CharField(max_length=50, verbose_name='گزینه چهارم')),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], help_text='گزینه درست را انتخاب کنید', max_length=7, verbose_name='پاسخ')),
                ('status', models.BooleanField(default=False, help_text='وضعیت انتشار سوال', verbose_name='وضعیت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz_app.category')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها',
            },
        ),
    ]
