# Generated by Django 4.2.11 on 2024-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.RenameField(
            model_name='userresult',
            old_name='correct',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='userresult',
            old_name='totall',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='userresult',
            old_name='fullname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userresult',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='آخرین تغییر '),
        ),
    ]
