# Generated by Django 5.0.6 on 2024-07-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_userresult_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
