# Generated by Django 5.0.6 on 2024-07-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='تصویر مربوط به سوال', null=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
